---
title: "pollen accumulation"
author: "Lucia Weinman"
date: "2/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(furrr)
library(parallel)
library(vegan)
library(bipartite)
```


```{r colleen's data - this is the observed pollen data}
#colleen's data
pollen<-read.csv("PollenData_formatted_4feb.csv")
colleen<-read.csv("forest_pollen_spec.csv")
pollens<-right_join(select(colleen, uniqueID,genus, species, site, date), select(pollen, -beeID))
pollens<-unite(pollens, bee, genus, species)
pollens<-pollens %>%
  mutate(pollen=replace(pollen, pollen=="na", "")) %>%
  as.data.frame()
#individual-level
individualpollens<-pollens%>%
  group_by(site, date, bee, uniqueID, pollen)%>%
  summarize(counts=n())
#wide format
indpollens_wide<-spread(individualpollens, pollen, counts)

#species level
speciespollens<-pollens%>%
  group_by(site, date, bee, pollen)%>%
  summarize(counts=n())

#wide format
sppollens_wide<-spread(drop_na(speciespollens[,c(1, 3:5)], pollen), pollen, counts)


```

```{r michael's data}
mrdat<-read.csv("data/2016_male_bee_dataset.csv")

fbees<-(mrdat %>% 
         filter(bee_sex=="F") 
        %>% group_by(site, sampling_round)) 

#plant use at species level in visit data, for Baldpate sampling round 2

Bald_visits<-filter(mrdat, site =="Baldpate", sampling_round=="2")
Bald_visits<- unite(Bald_visits, "plant", c("plant_genus", "plant_species"))
Bvisits<-Bald_visits%>%
  group_by(bee, plant )%>%
  summarize(visits=n())

B2visits<-spread(Bvisits, plant, visits)
B2visits<-B2visits[,order(colSums(-B2visits,na.rm=TRUE))]
B2visits<-B2visits[order(rowSums(-B2visits, na.rm=T)),]
B2visits<-B2visits%>%
  select(bee, everything())
write.csv(B2visits, "B2visits.csv")
#########POLLEN STUFF

#####SIMULATING POLLEN DATA; each individual of each species samples plants in proportion to 
#that's species' plant visits; each individual can visit n flowers in a foraging bout 
###(lucydat1 is 10 visits; the code below draws # of viists from a poisson dist.)
nc<-detectCores()-1
plan(strategy=multiprocess, workers=nc)

lucydat<-future_map_dfr(1:nrow(fbees), function(x){
    thissite<-fbees[[x, "site"]]
    thisround<-fbees[[x, "sampling_round"]]
    thisspecies<-fbees[[x, "bee"]]
    out<-fbees %>% 
        filter(site==thissite & sampling_round== thisround & bee == thisspecies) %>% 
        sample_n(rpois(1,2), replace=T)  %>%
        group_by(site, sampling_round, bee, sociality, plant_genus, plant_species) %>%
        summarize(pollen_units=n(), uID=fbees[[x,"uniqueID"]])
    return(out)
} )

lucydat<-lucydat%>%
  unite("plant",c("plant_genus", "plant_species"))
write.csv(lucydat, "lucydat1_pois.csv")

lucydat1<-read_csv("lucydat1.csv")
colleen<-read.csv("")
head(lucydat1)
lucydat1<-lucydat1%>%
  unite("plant",c("plant_genus", "plant_species"))

```

```{r looking at diversities of pollen in malebee simulated pollen data}
#shannon and richness of individual loads at each site and round
h<-c(2,4,6)
h/sum(h)
simpson<-function(h){sum((h/sum(h))^2)}
simpson(h)
diversities<-lucydat1%>%
  group_by(bee,uID, site, sampling_round)%>%
  summarise(richness=n(), shannon=exp(diversity(pollen_units, index="shannon")), 
            simpson= 1/simpson(pollen_units))

#i don't know what this is, might have been a first stab at an individual accumualtion curve
n<-sample(filter(lucydat1, site=="Baldpate" &sampling_round== "1")$uID,50, replace=T)

#looking at individual richness, simpson and shannon of lucydat1 at Baldpate
hist(filter(diversities, site=="Baldpate")$richness)
hist(filter(diversities, site=="Baldpate")$shannon)
hist(filter(r, site=="Baldpate")$simpson)
plot(filter(r, site=="Baldpate")$richness,filter(r, site=="Baldpate")$shannon)
plot(filter(r, site=="Baldpate")$richness,filter(r, site=="Baldpate")$simpson)

##individual load diversity by bee species at Baldpate
Bald<-filter(diversities, site=="Baldpate")
Bald1<-filter(Bald, sampling_round=="1")
Bald1<-arrange(Bald1, bee)
Bald1
Bald1
ggplot(Bald1, aes(x=bee, y=richness) )+
  geom_jitter()
```

```{r INDIVIDUAL LEVEL POLLEN STUFF}
#######FOR EACH BEE SPECIES, ACCUMULATION OF POLLEN TAXA ACROSS INDIVIDUAL LOADS.
#pollen accumulation(across individuals) for abundant species at Bowman's Hill Preserve (all #dates)
#drop NA pollens
indpollens_noNAs<-individualpollens%>%drop_na(pollen)
BHP<-filter(indpollens_noNAs, site=="BHP")
thing<-group_by(BHP, bee)%>%
  summarise(n=length(unique(uniqueID)))
BHP<-filter(BHP, site=="BHP", bee%in%filter(thing, n>5)$bee)
species<-unique(BHP$bee)
blah<-c("richness","iteration","individuals","species")

for (k in 1:length(species)){
  sp<-filter(BHP, bee==species[k])
  IDs<-unique(sp$uniqueID)
for (j in 1:length(IDs)){
  #comb<-combn(IDs,j)
for(i in 1:50){#ncol(comb))
sampleIDs<-filter(sp, uniqueID%in%IDs[sample(length(IDs), j, replace=F)])#comb[,i]))


blah<-rbind(blah,c(length(unique(sampleIDs$pollen)),i,j,k)) 

}}
}

blah<-as.data.frame(blah)
names(blah)<-c("richness","iteration","individuals","species")
blah<-blah[2:length(blah$richness),]
blah$individuals<-as.numeric(as.character(blah$individuals))
blah$richness<-as.numeric(as.character(blah$richness))

ggplot(blah, aes(x=individuals, y=richness))+
  geom_boxplot(aes(group=individuals))+
  facet_wrap(~species)+
  labs(title="Accumulation of pollen taxa across individuals")



```

```{r}
#############BEE-SPECIES LEVEL pollen stuff
#bee species level pollen composition; the number of "grains" of each plant collected by each bee #species 

speciespollen<-lucydat1%>%
  group_by(site, sampling_round, bee, plant)%>%
  mutate(grains=sum(pollen_units))

pollencomp<-select(speciespollen, c("site", "sampling_round", "bee", "plant", "grains"))
pollencomp<-unique(pollencomp)
pollencomp<-arrange(pollencomp, bee)

#just Baldpate sampling round 2
B2comp<-filter(pollencomp, site =="Baldpate" & sampling_round=="2")

B2comp_wide<-spread(B2comp, plant, grains)
B2comp_wide<-B2comp_wide[,4:24]
B2comp_wide<-B2comp_wide[,order(colSums(-B2comp_wide,na.rm=TRUE))]
B2comp_wide$rows<-rowSums(B2comp_wide, na.rm=T)
B2comp_wide$bee<-spread(B2comp, plant, grains)$bee

B2comp_wide<-B2comp_wide%>%
  arrange(desc(rows))

B2comp_wide<-B2comp_wide%>%
  select(bee, everything())
```

```{r apply threshold to observed data to determine important/dominant pollen taxa}
#select minimum set of pollens that meet 80% threshold for each species. subset full species by pollen taxa data frame

## data frame to get number of each pollen taxa collected by each bee species at each site
sppollens_alldates<-pollens%>%
  group_by(site, bee, pollen)%>%
  summarize(counts=n())

sppollens_noNAs<-sppollens_alldates%>%drop_na(pollen)

##dropping NAs from the individual pollen data
indpollens_noNAs<-individualpollens%>%drop_na(pollen)

#set lower bound for bee species sample size at each site
u=4

sites<-unique(droplevels(sppollens_noNAs$site))
dominants<-data.frame(site=NA, bee=NA, pollen=NA, counts=NA)

for (j in 1:length(sites)){
  #subset the individual pollen data by site
 indSITE<-filter(droplevels(indpollens_noNAs), site==sites[j])
 #get sample size for each bee species (number of individuals of each bee)
thing<-group_by(indSITE, bee)%>%
  summarise(n=length(unique(uniqueID)))

#subset bee species pollen data by  site
SITE<-filter(droplevels(sppollens_noNAs), site==sites[j])

#filter out bees for which caught more than "u" individuals at that site
SITE2<-filter(SITE, bee%in%filter(thing, n>u)$bee)
species<-unique(SITE2$bee)

#for each bee species, determine what the 80% threshold is
for(i in 1:length(species)){
  spp<-filter(SITE2, bee==species[i])
  spp<-arrange(spp, desc(counts))
  summ<-sum(spp$counts)
  thresh<-0.8*summ
  y<-1:length(spp$pollen)+2 #,"v", "meetthresh")
  
#starting with the pollen it collected the most of, cumulatively add all pollen taxa and ask whether the threshold is met.
 for(v in 1:nrow(spp)){
  min<-unlist(c(spp[1:v, 4], rep(0,nrow(spp)-v)))
  d<-sum(min)>=thresh
  #y will have 1 row for each combination of pollen taxa
  y<-rbind(y, c(min, v, d))
 }

y<-as.data.frame(y)
names(y)<-c(as.character(spp$pollen), "v", "meetthresh")
#how many rows (combinations of taxa) did not meet the threshold?
x<-nrow(filter(y[-1,], meetthresh==0))

z<-y[-1,]
#which pollen taxa are required to meet the threshold
dominant<-names(y)[which(z[x+1,-c(length(y)-1, length(y))]>0)]

#save that pollen
dominants <-rbind(as.data.frame(dominants[,1:3]), as.data.frame(spp[c(which(as.character(spp$pollen)%in%dominant)),1:3]))
}  

}

#there will be a lot of warnings saying that "number of columns of result is not a multiple of vector length", i have been ignoring them because i think it is all working as intended.
```

```{r observed accumulation of dom pollens across species, all sites}



acc<-c("richness","combination","#species")
species<-unique(dominants$bee)
for (j in 1:length(species)){
  #comb<-combn(species,j)
for(i in 1:35){
sample<-filter(dominants, bee%in%sample(species, j, replace=F))
acc<-rbind(acc,c(length(unique(sample$pollen)),i,j)) 
}
}


acc<-as.data.frame(acc)
names(acc)<-c("richness","combination","species")
acc<-acc[-1,]
acc$species<-as.numeric(as.character(acc$species))
acc$richness<-as.numeric(as.character(acc$richness))

ggplot(acc, aes(x=species, y=richness))+
  geom_boxplot(aes(group=species))+
  labs(title="Accumulation of pollen taxa across bee species")


means<-acc[,c(1,3)]%>%
  group_by(species)%>%
  summarize(mean=mean(richness))

 #ggplot(means, aes(x=species, y=mean))+
  #geom_line()+
 # labs(title="Mean accumulation of pollen taxa across bee species") 
```
NULL DATA
```{r null data, randomizing within sites}
nullpollens<-data.frame(bee=NA, pollen=NA, iteration=NA, site=NA)
 for(q in 1:50){
for (j in 1:length(sites)){
indSITE<-filter(droplevels(indpollens_noNAs), site==sites[j])

beecounts<-group_by(indSITE, bee)%>%
  summarise(n=length(unique(uniqueID)))
bigbeecounts<-filter(beecounts, bee%in%filter(beecounts, n>u)$bee)
species<-unique(bigbeecounts$bee)

pollenSITEwide<-filter(droplevels(filter(sppollens_wide, bee%in%filter(beecounts, n>u)$bee)), site==sites[j])
plantSAD<-as.numeric(colSums(pollenSITEwide[,-(1:3)], na.rm=T))
plantsgathered<-gather(pollenSITEwide, pollen, counts, -site, -date, -bee)
plants<-as.data.frame(cbind(unique(plantsgathered$pollen), plantSAD))

for (i in 1:length(species)){
  sp<-filter(bigbeecounts, bee==species[i])
  null<-as.data.frame(cbind(c(rep(species[i], sp$n)),c(sample(as.character(plants$V1), sp$n, replace=T, prob=plantSAD)), c(rep(q, sp$n)), c(rep(as.character(sites[j]), sp$n))))
names(null)<-names(nullpollens)
  nullpollens<-rbind(nullpollens, null)
}
}
 }

#need to reformat nullpollens so that there's counts of each pollen for each species 
gathered<-nullpollens[-1,]%>%
  group_by(iteration, site, bee, pollen)%>%
  summarise(counts=n())

#then can apply the threshold to null data
nulldominants<-data.frame(iteration=NA, site=NA, bee=NA, pollen=NA, counts=NA)
for(q in 1:50){
 whichiter <-filter(gathered, iteration==q)
for (j in 1:length(sites)){
SITE<-filter(droplevels(whichiter), site==sites[j])
species<-unique(SITE$bee)

for(i in 1:length(species)){
  spp<-filter(SITE, bee==species[i])
  spp<-arrange(spp, desc(counts))
  summ<-sum(spp$counts)
  thresh<-0.8*summ
  y<-1:length(spp$pollen)+3 #,"v", "meetthresh")

for(v in 1:nrow(spp)){
  min<-unlist(c(spp[1:v, 5], rep(0,nrow(spp)-v)))
  d<-sum(min)>=thresh
  y<-rbind(y, c(min, v, d, q))
 }

y<-as.data.frame(y)
names(y)<-c(as.character(spp$pollen), "v", "meetthresh", "iteration")
x<-nrow(filter(y[-1,], meetthresh==0))
z<-y[-1,]
dominant<-names(y)[which(z[x+1,-c(length(y)-2,length(y)-1, length(y))]>0)]
nulldompoll<-as.data.frame(spp[c(which(as.character(spp$pollen)%in%dominant)),-5])
names(nulldompoll)<-names(nulldominants[,-5])
nulldominants <-rbind(as.data.frame(nulldominants[,-5]),nulldompoll)

}  

}
}
#remove extra row at top
nulldominants<-nulldominants[-1,]

#then can do the null  accumulation 
nullacc<-c("richness","combination","#species", "iteration")

for (q in 1:50){

  whichdomiter<-filter(nulldominants, iteration ==q)
#for (k in 1:length(sites)){
# SITE<-filter(whichdomiter, site==sites[k])
 species<-unique(whichdomiter$bee)
for (j in 1:length(species)){
  for(i in 1:35){
  combination<-filter(whichdomiter, bee%in%sample(species, j, replace=F))
nullacc<-rbind(nullacc,c(length(unique(combination$pollen)),i,j,q)) 

}
}
}



nullacc<-as.data.frame(nullacc)
names(nullacc)<-c("richness","combination","species", "iteration")
nullacc<-nullacc[-1,]
nullacc$species<-as.numeric(as.character(nullacc$species))
nullacc$richness<-as.numeric(as.character(nullacc$richness))

ggplot(nullacc, aes(x=species, y=richness))+
  geom_boxplot(aes(group=species))+
  #facet_wrap(~iteration)+
  labs(title="null accumulation of dominant pollen taxa across bee species")

#mean across combinations of different species within iterations, so variation is from iterations
meannull<-nullacc%>%
  group_by(iteration, species)%>%
  summarise(mean=mean(richness))

#still have weird increase in variation with increasing # species.
ggplot(meannull, aes(x=species, y=mean))+
  geom_boxplot(aes(group=species))+
  #facet_wrap(~iteration)+
  labs(title="mean null accumulation of dominant pollen taxa across bee species")

#haven't gotten a plot with both observed and null to work yet
ggplot()+
  geom_line(acc, aes(x=species, y=richness,group=species))+
    geom_boxplot(nullacc, aes(x=species, y=richness, group=species))+
    labs(title="Accumulation of pollen taxa across bee species")

#



```

```{r null randomizing across sites (draw visits by each bee species at each site from big pollen  sad across all sites)}
wellsampled<-data.frame(bee=NA)
for(t in 1:length(sites)){
  #I want to save the names of the well-sampled bees at each site
  indSITE<-filter(droplevels(indpollens_noNAs), site==sites[t])
beecounts<-group_by(indSITE, bee)%>%
  summarise(n=length(unique(uniqueID)))
bigbeecounts<-filter(beecounts, bee%in%filter(beecounts, n>u)$bee)
wellsampled<-rbind(wellsampled, data.frame(bee=unique(bigbeecounts$bee)))
}
justwellsampled<-filter(sppollens_wide, bee %in% wellsampled$bee)

plantSAD<-as.numeric(colSums(justwellsampled[,-(1:3)], na.rm=T))
plantsgathered<-gather(justwellsampled, pollen, counts, -site, -date, -bee)
plants<-as.data.frame(cbind(unique(plantsgathered$pollen), plantSAD))

bignullpollens<-data.frame(bee=NA, pollen=NA, iteration=NA, site=NA)

 for(q in 1:50){
for (j in 1:length(sites)){
indSITE<-filter(droplevels(indpollens_noNAs), site==sites[j])
beecounts<-group_by(indSITE, bee)%>%
  summarise(n=length(unique(uniqueID)))
bigbees<-filter(beecounts, bee%in%filter(beecounts, n>u)$bee)
species<-unique(bigbees$bee)
for (i in 1:length(species)){
  sp<-filter(bigbees, bee==species[i])
  null<-as.data.frame(cbind(c(rep(species[i], sp$n)),c(sample(as.character(plants$V1), sp$n, replace=T, prob=plantSAD)), c(rep(q, sp$n)), c(rep(as.character(sites[j]), sp$n))))
names(null)<-names(bignullpollens)
  bignullpollens<-rbind(bignullpollens, null)
}
}
 }

#need to reformat bignullpollens so that there's counts of each pollen for each species 
biggathered<-bignullpollens[-1,]%>%
  group_by(iteration, site, bee, pollen)%>%
  summarise(counts=n())

#then can apply the threshold to null data
bignulldominants<-data.frame(iteration=NA, site=NA, bee=NA, pollen=NA, counts=NA)
for(q in 1:50){
 whichiter <-filter(biggathered, iteration==q)
for (j in 1:length(sites)){
SITE<-filter(droplevels(whichiter), site==sites[j])
species<-unique(SITE$bee)

for(i in 1:length(species)){
  spp<-filter(SITE, bee==species[i])
  spp<-arrange(spp, desc(counts))
  summ<-sum(spp$counts)
  thresh<-0.8*summ
  y<-1:length(spp$pollen)+3 #,"v", "meetthresh")

for(v in 1:nrow(spp)){
  min<-unlist(c(spp[1:v, 5], rep(0,nrow(spp)-v)))
  d<-sum(min)>=thresh
  y<-rbind(y, c(min, v, d, q))
 }

y<-as.data.frame(y)
names(y)<-c(as.character(spp$pollen), "v", "meetthresh", "iteration")
x<-nrow(filter(y[-1,], meetthresh==0))
z<-y[-1,]
dominant<-names(y)[which(z[x+1,-c(length(y)-2,length(y)-1, length(y))]>0)]
nulldompoll<-as.data.frame(spp[c(which(as.character(spp$pollen)%in%dominant)),-5])
names(nulldompoll)<-names(bignulldominants[,-5])
bignulldominants <-rbind(as.data.frame(bignulldominants[,-5]),nulldompoll)

}  

}
}

#remove extra row at top
bignulldominants<-bignulldominants[-1,]

#then can do the  accumulation 
bignullacc<-c("richness","combination","#species", "iteration")

for (q in 1:50){
  whichdomiter<-filter(bignulldominants, iteration ==q)
#for (k in 1:length(sites)){
# SITE<-filter(whichdomiter, site==sites[k])
 species<-unique(whichdomiter$bee)
for (j in 1:length(species)){
  for(i in 1:35){
  combination<-filter(whichdomiter, bee%in%sample(species, j, replace=F))
bignullacc<-rbind(bignullacc,c(length(unique(combination$pollen)),i,j,q)) 

}
}
}
bignulldominants

bignullacc<-as.data.frame(bignullacc)
names(bignullacc)<-c("richness","combination","species", "iteration")
bignullacc<-bignullacc[-1,]
bignullacc$species<-as.numeric(as.character(bignullacc$species))
bignullacc$richness<-as.numeric(as.character(bignullacc$richness))
View(bignullacc)
ggplot(bignullacc, aes(x=species, y=richness, color=iteration))+
  geom_jitter(aes(group=species))+
  #facet_wrap(~iteration)+
  labs(title="across site null accumulation of dominant pollen taxa across bee species")

#mean across combinations of different species within iterations, so variation is from iterations
meanbignull<-bignullacc%>%
  group_by(combination, species)%>%
  summarise(mean=mean(richness))

#i think the increase 
ggplot(meanbignull, aes(x=species, y=mean, color=as.numeric(as.character(combination))))+
  geom_point(aes(group=species))+
  #facet_wrap(~iteration)+
  labs(title="mean null accumulation of dominant pollen taxa across bee species")

```


